package com.virtue.csr.constants;

import java.text.SimpleDateFormat;
import java.util.Locale;

public interface CONSTANTS {
	
	String BLANK = "";
	String WHITE_SPACE = " ";
	String LINE_SEPERATOR = "\n";
	String CSV_FIELD_SEPERATOR = ",";
	String DEFAULT_PARTNER_CODE = "VIRTUE";
	
	String SAT_SCORE="SAT";
	String ACT_SCORE="ACT";
	String STATE_MINNESOTA="Minnesota";
	String YES="yes";
	
	int DEFAULT_ROWLIMIT = 1000;
	int TUTION_FEE = 15142;
	double MISCELLANEOUS_CAP = 9930;
	
	SimpleDateFormat INPUT_DATEFORMAT = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
	SimpleDateFormat OUTPUT_DATEFORMAT = new SimpleDateFormat("MMM d, yyyy", Locale.ENGLISH);
	String LOGGER_MSG = "inside method  ->>  {}";
	String BASE_YEAR_KEY = "base.year";
	String HOME_STATE_KEY = "home.state";
	String RESULT_OBJECT_KEY = "result.object";
	
	double EMPLOYMENT_EXPENSE_ALLOWANCE_LOWER_LIMIT = 4000;
	double EMPLOYMENT_EXPENSE_ALLOWANCE_MUL_FACTOR = 35;
	int ENROLLEMNT_GT_HALF_NO_IN_COLLEGE = 2;
	int ENROLLEMNT_LT_HALF_NO_IN_COLLEGE = 1;
	double REMAINING_NEED_LIMIT_1 = 3500;
	double REMAINING_NEED_LIMIT_2 = 5500;
	double REMAINING_NEED_LIMIT_3 = 7500;
	double DSL_VALUE = 3500;
	double DUSL_VALUE = 2000;
	double FWS_VALUE = 2000;
	
	double SCENARIO_A_ASSET_CONVERSION_RATE = 0.12;
	double SCENARIO_A_STUDENT_INCOME_PROTECTION_ALLOWANCE = 6840;
	double SCENARIO_A_ASSESMENT_OF_AI = 0.5;
	double SCENARIO_A_STUDENT_ASSESMENT_RATE = 0.2;
	double SCENARIO_A_TUTION_CAP = 15142;
	double SCENARIO_A_MISC_CAP = 9930;
	double SCENARIO_A_STATE_BUDGET_MUL_FACTOR=0.50;
	double SCENARIO_A_PARENTS_CONTRIB_MUL_FACTOR=0.82;

	
	double SCENARIO_B_IP_ALLOWANCE_UNMARRIED = 10640;
	double SCENARIO_B_IP_ALLOWANCE_MARRIED_GT_HALF = 10640;
	double SCENARIO_B_IP_ALLOWANCE_MARRIED_LT_HALF = 17060;
	double SCENARIO_B_ASSESMENT_RATE = 0.5;
	double SCENARIO_B_ASSET_CONVERSION_RATE = 0.2;
	double SCENARIO_B_STATE_BUDGET_MUL_FACTOR=0.50;
	double SCENARIO_B_EFC_MUL_FACTOR=0.38;
	double SCENARIO_B_TUTION_CAP = 15142;
	double SCENARIO_B_MISC_CAP = 9930;
	
	double SCENARIO_C_ASSET_CONVERSION_RATE = 0.07;
	double SCENARIO_C_TUTION_CAP = 15142;
	double SCENARIO_C_MISC_CAP = 9930;
	double SCENARIO_C_EFC_MUL_FACTOR=0.74;
	double SCENARIO_C_STATE_BUDGET_MUL_FACTOR=0.50;
	int MIN_INDEPENDENT_AGE = 24;
	double INTEREST_PERCENT_DSL = 5.05;
	double INTEREST_PERCENT_DUSL = 5.05;
	double INTEREST_PERCENT_OTHER_LOANS = 8;
	int PAYMENT_TERM_IN_MONTHS = 120;
	double CHRISTIAN_DISC = 1500;
	double ALUMNI_DISC = 1500;
	double MAX_AGI_PER_ADDITIONAL_MEMBER = 4500.0; 
	
}
